name: Validate Merge

on:
  pull_request:
    branches:
      - main

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is from dev
        run: |
          if [ "${{ github.base_ref }}" = "main" ] && [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Merges to main are only allowed from dev branch."
            exit 1
          fi
